version: "3"

services:
  nextjs:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
